approvedGitRepositories:
  - "https://github.com/ahultgren/async-eventemitter.git"
  - "https://github.com/debris/bignumber.js.git"
  - "https://github.com/ethereumjs/ethereumjs-abi.git"
  - "https://github.com/foundry-rs/forge-std.git"
  - "https://github.com/frozeman/bignumber.js-nolookahead.git"

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d
