[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@aragon/=node_modules/@aragon/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "ens/=node_modules/@aragon/os/contracts/lib/ens/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "math/=node_modules/@aragon/os/contracts/lib/math/",
    "misc/=node_modules/@aragon/os/contracts/lib/misc/",
    "openzeppelin-solidity/=node_modules/openzeppelin-solidity/",
    "token/=node_modules/@aragon/os/contracts/lib/token/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
