# Lido Protocol Upgrade Parameters - Mainnet Configuration
# This file contains deployment parameters for upgrading Lido protocol contracts on Ethereum mainnet

[chainSpec]
# Ethereum consensus layer specifications
# TODO: take onchain?
slotsPerEpoch = 32                    # Number of slots per epoch in Ethereum consensus
secondsPerSlot = 12                   # Duration of each slot in seconds
genesisTime = 1606824023              # Ethereum mainnet genesis timestamp
depositContract = "0x00000000219ab540356cBB839Cbe05303d7705Fa"  # Official ETH2 deposit contract

# Gate seal configuration for vault operations
[gateSealForVaults]
address = "0x0000000000000000000000000000000f00f00F00"  # TODO: update the placeholder

# Validator exit delay verifier configuration for managing validator exits
[validatorExitDelayVerifier]
# Generalized indices for validator state verification in Ethereum consensus
gIFirstValidatorPrev = "0x0000000000000000000000000000000000000000000000000096000000000028"
gIFirstValidatorCurr = "0x0000000000000000000000000000000000000000000000000096000000000028"
gIFirstHistoricalSummaryPrev = "0x000000000000000000000000000000000000000000000000000000b600000018"
gIFirstHistoricalSummaryCurr = "0x000000000000000000000000000000000000000000000000000000b600000018"
gIFirstBlockRootInSummaryPrev = "0x000000000000000000000000000000000000000000000000000000000040000d"
gIFirstBlockRootInSummaryCurr = "0x000000000000000000000000000000000000000000000000000000000040000d"

# Vault hub configuration for managing staking vaults
[vaultHub]
relativeShareLimitBP = 1000           # Relative share limit in basis points (10%)

# Lazy oracle configuration for delayed reward calculations
[lazyOracle]
quarantinePeriod = 259200             # Quarantine period in seconds (3 days) before rewards are distributed
maxRewardRatioBP = 350                # Maximum reward ratio in basis points (3.5%)

# Predeposit guarantee configuration for validator deposit guarantees
[predepositGuarantee]
genesisForkVersion = "0x00000000"     # Ethereum mainnet genesis fork version
gIndex = "0x0000000000000000000000000000000000000000000000000096000000000028"  # Generalized index for state verification
gIndexAfterChange = "0x0000000000000000000000000000000000000000000000000096000000000028"
changeSlot = 0                        # Slot number when the change takes effect

# Delegation module configuration for liquid delegation
[delegation]
wethContract = "0x94373a4919B3240D86eA41593D5eBa789FEF3848"  # WETH contract address for wrapped ETH operations

# Operator grid configuration for managing staking operators
[operatorGrid]
# Default tier parameters for operator classification and fee structure
[operatorGrid.defaultTierParams]
shareLimitInEther = "1000"            # Share limit per tier in ETH
reserveRatioBP = 2000                 # Reserve ratio in basis points (20%)
forcedRebalanceThresholdBP = 1800     # Threshold for forced rebalancing in basis points (18%)
infraFeeBP = 500                      # Infrastructure fee in basis points (5%)
liquidityFeeBP = 400                  # Liquidity provision fee in basis points (4%)
reservationFeeBP = 100                # Reservation fee in basis points (1%)

[burner]
isMigrationAllowed = true             # Must be on for the upgrade to work (for scratch is it false)

# Oracle and consensus version configuration
[oracleVersions]
vebo_consensus_version = 4            # Validators Exit Bus Oracle consensus version
ao_consensus_version = 4              # Accounting Oracle consensus version

# Application versions for Aragon apps
[aragonAppVersions]
nor_version = [6, 0, 0]              # Node Operators Registry version
sdvt_version = [3, 0, 0]             # Simple DVT version

# ================================================================================================
# TRIGGERABLE WITHDRAWALS (TW) UPGRADE PARAMETERS
# ================================================================================================
# All parameters related to the Triggerable Withdrawals upgrade are grouped here for easy access

# TW Gateway configuration for managing validator exit requests
[triggerableWithdrawalsGateway]
maxExitRequestsLimit = 13000          # Maximum number of exit requests that can be processed
exitsPerFrame = 1                     # Number of exits processed per frame
frameDurationInSec = 48               # Duration of each processing frame in seconds

# TW Exit management configuration
[triggerableWithdrawals]
exit_events_lookback_window_in_slots = 7200  # Lookback window for exit events in slots (1 day)
nor_exit_deadline_in_sec = 1800       # Node operator registry exit deadline in seconds (30 minutes)
