name: Common setup

on: workflow_call

runs:
  using: "composite"
  steps:
    - name: Enable corepack
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
