name: Contract Bug Report
description: File a bug report in a contract.
title: "[Bug]: "
labels: ["bug", "contracts"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Important! If the bug may potentially lead to loss of user funds, denial of service, governance hijacks, data breaches, and data leaks, please refer to [Lido Bug Bounty](https://immunefi.com/bug-bounty/lido/information/).
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short summary of the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Expected behavior of the contract without the bug
    validations:
      required: true
  - type: textarea
    id: Impact
    attributes:
      label: Potential Impact
      description: Bug's impact and possible consequences
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Instructions to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solutions
      description: Possible ways to fix the bug
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      options:
        - label: I agree to follow [Code of Conduct](https://github.com/lidofinance/core/blob/master/CODE_OF_CONDUCT.md).
          required: true
        - label: I have read [Lido Contribution Guide](https://github.com/lidofinance/core/blob/master/CONTRIBUTING.md).
          required: true
