name: Analysis

on:
  pull_request:
  push:
    branches: [master]

jobs:
  slither:
    name: Slither
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Versions
        run: >
          poetry --version &&
          python --version &&
          echo "slither $(poetry run slither --version)" &&
          poetry run slitherin --version

      - name: Run slither
        run: >
          poetry run slither . --no-fail-pedantic --sarif results.sarif

      - name: Check results.sarif presence
        id: results
        if: always()
        shell: bash
        run: >
          test -f results.sarif &&
          echo 'value=present' >> $GITHUB_OUTPUT ||
          echo 'value=not' >> $GITHUB_OUTPUT

      - name: Upload results.sarif file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: ${{ always() && steps.results.outputs.value == 'present' }}
        with:
          sarif_file: results.sarif
