name: Analysis

on:
  pull_request:
  push:
    branches: [master]

jobs:
  slither:
    name: Slither
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Versions
        run: >
          poetry --version &&
          python --version &&
          echo "slither $(poetry run slither --version)" &&
          poetry run slitherin --version

      - name: Run slither
        run: >
          poetry run slither . --no-fail-pedantic --sarif results.sarif

      - name: Check results.sarif presence
        id: results
        if: always()
        shell: bash
        run: >
          test -f results.sarif &&
          echo 'value=present' >> $GITHUB_OUTPUT ||
          echo 'value=not' >> $GITHUB_OUTPUT

      - name: Upload results.sarif file
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        if: ${{ always() && steps.results.outputs.value == 'present' }}
        with:
          sarif_file: results.sarif
