name: Coverage

on:
  pull_request:
  push:
    branches: [master]

jobs:
  coverage:
    name: Hardhat / Unit Tests
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=6400

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Collect coverage
        run: yarn test:coverage

      - name: Produce the coverage report
        uses: lidofinance/coverage-action@b036d2354d1aeffd162da773e5be853283d28888
        with:
          path: ./coverage/cobertura-coverage.xml
          publish: true
          threshold: 95
          diff: true
          diff-branch: master
          diff-storage: _core_coverage_reports
          coverage-summary-title: "Hardhat Unit Tests Coverage Summary"
          togglable-report: true
