name: Coverage

on:
  pull_request:
  push:
    branches: [master]

jobs:
  coverage:
    name: Hardhat / Unit Tests
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Collect coverage
        run: NODE_OPTIONS="--max-old-space-size=10240" yarn test:coverage
        timeout-minutes: 30

      - name: Produce the coverage report
        uses: lidofinance/coverage-action@a94351baa279790f736655b1891178b1515594ea
        with:
          path: ./coverage/cobertura-coverage.xml
          publish: true
          threshold: 95
          diff: true
          diff-branch: master
          diff-storage: _core_coverage_reports
          coverage-summary-title: "Hardhat Unit Tests Coverage Summary"
          togglable-report: true
