name: Linters

on: [push]

jobs:
  lint:
    name: Solidity and TypeScript linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Solidity linters
        run: npm run lint:sol

      - name: Run TS linters
        run: npm run lint:ts

  types:
    name: TypeScript types check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate typechain types
        run: npm run hardhat compile

      - name: Run TypeScript types check
        run: npm run typecheck
