name: Releases

on:
  release:
    types: [published] # stable and pre-releases

permissions:
  contents: write

jobs:
  release-abis:
    name: ABIs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Extract ABIs
        run: yarn abis:extract

      - name: Create ABIs archive
        run: zip -j ABIs.zip lib/abi/*.json

      - name: Upload ABIs to release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ABIs.zip
