name: Releases

on:
  release:
    types: [published] # stable and pre-releases

permissions:
  contents: write

jobs:
  release-abis:
    name: ABIs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Compile contracts
        run: yarn compile

      - name: Extract ABIs
        run: yarn extract-abis

      - name: Create ABIs archive
        run: zip -j ABIs.zip lib/abi/*.json

      - name: Upload ABIs to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ABIs.zip
