name: Integration Tests

on: [push]

jobs:
  test_hardhat_integration:
    name: Hardhat
    runs-on: ubuntu-latest
    timeout-minutes: 120

    services:
      hardhat-node:
        image: feofanov/hardhat-node:2.22.9
        ports:
          - 8545:8545
        env:
          ETH_RPC_URL: "${{ secrets.ETH_RPC_URL }}"

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Set env
        run: cp .env.example .env

      - name: Run integration tests
        run: yarn test:integration:fork
        env:
          LOG_LEVEL: debug
