name: Build and push integration tests image

on:
  push:
    branches:
      - feat/docker-tests

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mainnet fork image
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/lidofinance/core-integration-tests:${{ github.ref_name }}
          build-args: |
            HH_CONFIG=hardhat.config.mainnet-fork.ts
