name: Unit Tests

on: [push]

jobs:
  test_hardhat_unit:
    name: Hardhat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Run unit tests
        run: NODE_OPTIONS="--max-old-space-size=10240" yarn test

  test_foundry_fuzzing:
    name: Foundry / Fuzzing & Invariants
    if: github.ref_name != 'develop' && github.ref_name != 'master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Print forge version
        run: forge --version

      - name: Run fuzzing and invariant tests
        run: forge test

  test_foundry_fuzzing_deep:
    name: Foundry / Fuzzing & Invariants (deep)
    if: github.ref_name == 'develop' || github.ref_name == 'master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Print forge version
        run: forge --version

      - name: Run fuzzing and invariant tests (deep profile, 10k runs)
        run: FOUNDRY_PROFILE=deep forge test
