name: Verify State

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    paths:
      - ".github/workflows/verify-state.yml"
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC

jobs:
  run_state_mate_hoodi:
    name: Hoodi State
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      STATE_MATE_BRANCH: "main"
      ETH_HOODI_RPC_URL: "https://hoodi.drpc.org"
      ETHERSCAN_TOKEN: "${{ secrets.ETHERSCAN_TOKEN }}"

    steps:
      - name: Checkout state-mate
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: lidofinance/state-mate
          ref: ${{ env.STATE_MATE_BRANCH }}

      - uses: ./.github/actions/setup

      - name: Run state-mate (Hoodi)
        run: yarn start configs/lido/testnet --quiet

  run_state_mate_mainnet:
    name: Mainnet State
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      STATE_MATE_BRANCH: "main"
      ETH_RPC_URL: "${{ secrets.ETH_RPC_URL }}"
      ETHERSCAN_TOKEN: "${{ secrets.ETHERSCAN_TOKEN }}"

    steps:
      - name: Checkout state-mate
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: lidofinance/state-mate
          ref: ${{ env.STATE_MATE_BRANCH }}

      - uses: ./.github/actions/setup

      - name: Run state-mate (Mainnet)
        run: yarn start configs/lido/mainnet --quiet
